proxy,google_trends_access,response_time,error
http://150.136.247.129:1080,False,1.6245579719543457,HTTP Error: 429
http://78.129.155.75:8080,False,5.1658313274383545,HTTP Error: 429
http://83.217.23.35:8090,False,0.8653545379638672,HTTP Error: 429
http://51.68.175.56:1080,False,,"HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /trends/explore (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000223B37602C0>, 'Connection to 51.68.175.56 timed out. (connect timeout=15)')))"
http://168.196.114.89:56000,False,,"HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /trends/explore (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000223B378B380>, 'Connection to 168.196.114.89 timed out. (connect timeout=15)')))"
http://158.160.52.208:8090,False,,"HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /trends/explore (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))"
http://46.209.199.145:8090,False,,"HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /trends/explore (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000223B365F5C0>, 'Connection to 46.209.199.145 timed out. (connect timeout=15)')))"
http://103.115.239.14:1111,False,9.316712379455566,HTTP Error: 429
http://216.229.112.25:8080,False,2.597337245941162,HTTP Error: 429
http://5.189.174.81:8888,False,4.312018156051636,HTTP Error: 429
http://93.126.6.68:3128,False,,"HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /trends/explore (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000223B37621B0>, 'Connection to 93.126.6.68 timed out. (connect timeout=15)')))"
http://45.140.143.77:18080,False,0.15927529335021973,HTTP Error: 429
http://177.93.16.66:8080,False,,"HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /trends/explore (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000223B37602C0>, 'Connection to 177.93.16.66 timed out. (connect timeout=15)')))"
http://91.107.182.7:1080,False,,"HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /trends/explore (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000223B3761F40>, 'Connection to 91.107.182.7 timed out. (connect timeout=15)')))"
http://34.246.112.243:80,False,,"HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /trends/explore (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000223B1DF8680>, 'Connection to 34.246.112.243 timed out. (connect timeout=15)')))"
